services:
  core_bundle.validator.validedate:
       class: CoreBundle\Validator\DategoodValidator
       arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
       tags:
            - { name: validator.constraint_validator, alias: core_bundle_dategood }
