services:
  core_bundle.validator.validedate:
       class: CoreBundle\Validator\ValideDateValidator
       arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
       tags:
            - { name: validator.constraint_validator, alias: core_bundle_validedate }
  core_bundle.validator.validereservationday:
       class: CoreBundle\Validator\ValideReservationDayValidator
       arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
       tags:
            - { name: validator.constraint_validator, alias: core_bundle_validereservation }


