<?php

namespace CoreBundle\Repository;

/**
 * TicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsRepository extends \Doctrine\ORM\EntityRepository
{
 // public function findTarifByType($age, $reduit){
 //   $qb = $this->createQueryBuilder('t')

 //   if ($reduit === true) {

 //    $tickets = $respository->findOneBy(array('type'=> ))

 //   }
 //  return $qb->getQuery()->getResult();
 // }
}
